development:
  adapter: postgresql
  encoding: unicode
  database: mongoid-dev
  pool: 5
  timeout: 5000
  username: johnfigueiredo
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: mongoid-test
  pool: 5
  timeout: 5000
  username: johnfigueiredo
  password:
